resolver: lts-9.1

compiler-check: newer-minor

# Local packages, usually specified by relative directory name
packages:
- .

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ generic-accessors-0.6.2.0
            , spatial-math-0.4.0.0
            , TypeCompose-0.9.12
            ]

# Override default flag values for local packages and extra-deps
flags:
  Plot-ho-matic:
    examples: true
