resolver: lts-10.3

compiler-check: newer-minor

# Local packages, usually specified by relative directory name
packages:
- .

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ generic-accessors-0.7.0.0
            , gio-0.13.5.0
            , gtk3-0.14.9
            , spatial-math-0.5.0.0
            ]

# Override default flag values for local packages and extra-deps
flags:
  Plot-ho-matic:
    examples: true
