resolver: lts-17.8

compiler-check: newer-minor

packages:
- .

extra-deps: [ generic-accessors-0.7.1.0
            , Chart-cairo-1.9.3
            , cairo-0.13.8.1
            , gio-0.13.8.1
            , glib-0.13.8.1
            , gtk3-0.15.5
            , gtk2hs-buildtools-0.13.8.0
            , pango-0.13.8.1
            , spatial-math-0.5.0.0
            ]

flags:
  Plot-ho-matic:
    examples: true
