#! /bin/bash
set -eu

APT="sudo apt-get -q -y"
CABAL_INSTALL_DEPS="cabal install --only-dependencies"

$APT update
$APT install libpango1.0-dev libcairo2-dev libglib2.0-dev
cabal install gtk2hs-buildtools
$CABAL_INSTALL_DEPS
